[package]
name = "conch-shell"
version = "0.1.2"
edition = "2024"
description = "Conch Shell"
license = "MIT"
repository = "https://github.com/prymul/conch"
homepage = "https://github.com/prymul/conch"
readme = "README.md"
authors = ["Mateo Elias Martinez"]

[[bin]]
name = "conch"
path = "src/main.rs"

[dependencies]

[package.metadata.deb]
maintainer = "Mateo Elias Martinez <mateo.martinez.spc@icloud.com>"
copyright = "2026, prymul"
license-file = ["LICENSE", "4"]
extended-description = "Conch Shell"
depends = "$auto"
section = "utils"
priority = "optional"
assets = [
    ["target/release/conch", "usr/bin/", "755"],
]
