[workspace]
resolver = "3"
members = [
    "crates/conch-lexer",
    "crates/conch-parser",
    "crates/conch-core",
    "crates/conch-builtins",
    "crates/conch",
    "tests/conch-difftest",
]

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/prymul/conch"
homepage = "https://github.com/prymul/conch"
authors = ["Mateo Elias Martinez"]

[workspace.dependencies]
conch-shell-lexer = { path = "crates/conch-lexer", version = "0.1.1" }
conch-shell-parser = { path = "crates/conch-parser", version = "0.1.1" }
conch-shell-core = { path = "crates/conch-core", version = "0.1.1" }
conch-shell-builtins = { path = "crates/conch-builtins", version = "0.1.1" }
